server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
        defaultZone: http://localhost:30761/eureka/

#
#
#  debug:
#    request: true
#
zuul:
  prefix:  /api
  routes:
    authenticationservice:
      path: /uua/**
      sensitiveHeaders:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    deviceservice: /device/**
  sensitiveHeaders: Cookie,Set-Cookie 
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8901/auth/oauth/token
      user-authorization-uri: http://localhost:8901/auth/oauth/authorize
      client-id: open-api
    resource:
      user-info-uri: http://localhost:8901/auth/user
      prefer-token-info: false
