#Default port is 8761
server:
  port: 30761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
          defaultZone: http://localhost:30761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
