version: "3.3"
services:
  eureka-server:
    image: "eureka-server:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    volumes:
    - /opt/device/eurekaserver:/usr/local/eurekaserver
#    network_mode: host
    ports:
      - "30761:30761"
#    extra_hosts:
#      - "host:10.13.0.124"
    healthcheck:
      test: curl --fail -s http://localhost:30761/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
