apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    run: eureka-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: eureka-server
        image: registry.cn-shenzhen.aliyuncs.com/cay914/eureka-service
        ports:
        - containerPort: 8761
          protocol: TCP
