version: "3.3"
services:
  eureka-server:
    image: "zuulsvr:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: zuulsvr
    volumes:
    - /opt/zuulsvr:/opt/device/zuulsvr
    network_mode: host
    ports:
      - "5555:5555"
    extra_hosts:
      - "host:192.168.3.25"
    healthcheck:
      test: curl --fail -s http://localhost:5555/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
