version: "3.3"
services:
  eureka-server:
    image: "eurekaserver:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    volumes:
    - /opt/device/eurekaserver:/usr/local/eurekaserver
    network_mode: host
    ports:
      - "30761:30761"
    extra_hosts:
      - "host:192.168.3.18"
    healthcheck:
      test: curl --fail -s http://localhost:30761/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
