version: "3.3"
services:
  eureka-server:
    image: "authentication-service:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: authentication-service
    volumes:
    - /opt/authentication-service:/opt/device/authentication-service
    network_mode: host
    ports:
      - "8901:8901"
    extra_hosts:
      - "host:192.168.3.25"
    healthcheck:
      test: curl --fail -s http://localhost:30761/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
