server:
  port: 9003
  servlet: 
    context-path: /swag

spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  deviceTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost

#Setting the logging levels for the service
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
    ip-address: 47.112.198.72
    non-secure-port: 29003
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
        defaultZone: http://eureka.codebattery.top/eureka/
    
        
security:
  oauth2:
    resource:
      user-info-uri: http://auth.codebattery.top/auth/user
